apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  index.html: |-
    <!DOCTYPE html>
    <html>
    <head>
    <title>Dev</title>
    </head>
    <body>

    <h1>test</h1>

    </body>
    </html>