apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-webserver
spec:
  template:
    replicas: 2
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
