apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-webserver
spec:
  template:
    replicas: 4
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        resources:
          limits:
            memory: "1Gi"
            cpu: "1"
          requests:
            cpu: "500"
            memory: "512Mi" 
        ports:
        - containerPort: 80
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1      
